"use client"
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from "@/components/ui/toaster"
import Provider from '@/components/Provider';

import { DownOutlined, SmileOutlined, LogoutOutlined,UploadOutlined, UserOutlined, VideoCameraOutlined} from '@ant-design/icons';
import { Layout, Menu, theme, Avatar, Space, Dropdown, Button, Flex, Tooltip } from 'antd';
import type { MenuProps } from 'antd';
import React from 'react';
import { MdWorkspacesOutline } from 'react-icons/md';
import Link from 'next/link';
import { signOut } from "next-auth/react";

const inter = Inter({ subsets: ['latin'] });

const { Header, Content, Footer, Sider } = Layout;


const itemsmenu: MenuProps['items'] = [
    {
        key: '1',
        icon: React.createElement(UserOutlined),
        label: (
            <a rel="noopener noreferrer" href="#">
                Test
            </a>
        ),
    },
    {
        key: '2',
        icon: React.createElement(VideoCameraOutlined),
        label: (
            <a rel="noopener noreferrer" href="#">
                Menu
            </a>
        ),
    },
];

const items: MenuProps['items'] = [
    {
        key: '1',
        label: (
            <a target="_blank" rel="noopener noreferrer" href="https://www.antgroup.com">
                1st menu item
            </a>
        ),
    },
    {
        key: '2',
        label: (
            <a target="_blank" rel="noopener noreferrer" href="https://www.aliyun.com">
                2nd menu item (disabled)
            </a>
        ),
        icon: <SmileOutlined />,
        disabled: true,
    },
    {
        key: '3',
        label: (
            <a target="_blank" rel="noopener noreferrer" href="https://www.luohanacademy.com">
                3rd menu item (disabled)
            </a>
        ),
        disabled: true,
    },
    {
        key: '4',
        danger: true,
        label: 'a danger item',
    },
];

export const metadatas: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

    const {
        token: { colorBgContainer, borderRadiusLG },
    } = theme.useToken();
    
  
    
  return (
    <html lang='en'>
      <body className={inter.className}>
       <Provider>
       <Layout style={{ minHeight: '100vh' }}>
            <Sider 
                style={{ background: colorBgContainer }}
                breakpoint="lg"
                collapsedWidth="0"
                onBreakpoint={(broken) => {
                    console.log(broken);
                }}
                onCollapse={(collapsed, type) => {
                    console.log(collapsed, type);
                }}
            >

                <div className="flex gap-x-4 items-center p-5">

                    <Link href='/antdadmin'>
                        <div className="bg-purple-800 text-white p-3 rounded-lg inline-block cursor-pointer duration-500">
                            <MdWorkspacesOutline size={20} />
                        </div>
                    </Link>
                    <h1 className="text-dark origin-left font-medium text-xl duration-200">
                        Company
                    </h1>
                </div>

                <Menu theme="light" mode="inline" defaultSelectedKeys={['4']} items={itemsmenu} />
            </Sider>
            <Layout>
            
                <Header className='flex border-l' style={{ padding: 0, background: colorBgContainer }} >
                    <div className='flex flex-shrink-0 items-center ml-auto'>
                        <Dropdown className='pr-2' menu={{ items }}>
                            <a onClick={(e) => e.preventDefault()}>
                                <Space>
                                    User
                                    <Avatar size="large" icon={<UserOutlined />} />
                                    <DownOutlined />
                                </Space>
                            </a>
                        </Dropdown>

                        <div className='pr-2 border-l pl-3 ml-3 space-x-1'>
                            <Flex wrap="wrap" gap="small">
                                <Tooltip>
                                    <Button shape="circle" icon={<LogoutOutlined />} onClick={() => signOut({
                                        redirect: true,
                                        callbackUrl: `${window.location.origin}/sign-in`,
                                    })} />
                                </Tooltip>
                            </Flex>
                        </div>
                    </div>


                </Header>
                {children}
                <Footer style={{ textAlign: 'center' }}>
                     © {new Date().getFullYear()} 
                </Footer>
            </Layout>
        </Layout>
        <Toaster />
       </Provider>
      </body>
    </html>
  );
}
