import Head from 'next/head';
import Image from 'next/image';
import { redirect } from 'next/navigation';
import Header from '@/components/admin/Header';
import Sidebar from '@/components/admin/Sidebar';
import { authOptions } from "@/lib/auth";
import { getServerSession } from "next-auth";

export default async function Home() {
    const session = await getServerSession(authOptions);

    if(session?.user)
    {
        return (
            <>
              <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
              </Head>
              <main className='bg-gray-100 min-h-screen'>
                <Sidebar> 
                  <Header />
                </Sidebar>
              </main>
            </>
          );
    }

    return redirect('/sign-in');
    //<h2 className="text-2xl"> please login to see this admin page</h2>
}
